version: 4.0.0-aci-{build}

build_script:
  - ps: |
    dotnet --info
    dotnet new --install . || exit 1
    
    mkdir testA
    pushd testA
    dotnet new freya || exit 1
    dotnet restore || exit 1
    dotnet build -c Release || exit 1
    popd

    mkdir testB
    pushd testB
    dotnet new freya -f hopac || exit 1
    dotnet restore || exit 1
    dotnet build -c Release || exit 1
    
test: off
