build_script:
  - ps: dotnet --info
  - ps: dotnet new --install .
    
  - ps: mkdir testA
  - ps: pushd testA
  - ps: dotnet new freya
  - ps: dotnet restore
  - ps: dotnet build -c Release
  - ps: popd

  - ps: mkdir testB
  - ps: pushd testB
  - ps: dotnet new freya -f hopac
  - ps: dotnet restore
  - ps: dotnet build -c Release
    
test: off
